# STQD6014 Data Science Project 1 (P166974)

PART 2 LISTS, DICTIONARIES AND LOOPING

In [1]:
# Dictionary storing info about 5 cities
cities = {
    "hanoi": {
        "country": "vietnam",
        "population_in_millions": 5.6,
        "landmarks": ["train street", "hoa lo prison", "mega grand world hanoi"],
        "dishes": ["banh mi", "pho", "vietnamese spring rolls"]
    },
    "phuket": {
        "country": "thailand",
        "population_in_millions": 0.5,
        "landmarks": ["kata beach", "old phuket town", "big buddha"],
        "dishes": ["pad thai", "tom yum goong", "pad krapaw"]
    },
    "vientiane": {
        "country": "laos",
        "population_in_millions": 1.0,
        "landmarks": ["patuxay monument", "pha that luang", "wat sisaket"],
        "dishes": ["sai oua", "nam khao", "khao poon nam paa"]
    },
    "phnom penh": {
        "country": "cambodia",
        "population_in_millions": 3.5,
        "landmarks": ["royal palace phnom penh", "silver pagoda", "independence monument"],
        "dishes": ["amok", "kuy teav", "lap khmer"]
    },
    "naypyidaw": {
        "country": "myanmar",
        "population_in_millions": 0.9,
        "landmarks": ["uppatasanti pagoda", "myoma market", "water fountain garden"],
        "dishes": ["nan gyi thoke", "burmese tofu", "mohinga"]
    }
}

# Printing information about the cities using loops
for city, info in cities.items():
    print("\n" + city.upper())
    print("Country: " + info['country'].title())
    print("Population: " + str(info['population_in_millions']) + " million")

    print("  Famous Landmarks:")
    for landmark in info["landmarks"]:
        print("\t- " + landmark.title())

    print("  Local Dishes:")
    for dish in info["dishes"]:
        print("\t- " + dish.title())


HANOI
Country: Vietnam
Population: 5.6 million
  Famous Landmarks:
	- Train Street
	- Hoa Lo Prison
	- Mega Grand World Hanoi
  Local Dishes:
	- Banh Mi
	- Pho
	- Vietnamese Spring Rolls

PHUKET
Country: Thailand
Population: 0.5 million
  Famous Landmarks:
	- Kata Beach
	- Old Phuket Town
	- Big Buddha
  Local Dishes:
	- Pad Thai
	- Tom Yum Goong
	- Pad Krapaw

VIENTIANE
Country: Laos
Population: 1.0 million
  Famous Landmarks:
	- Patuxay Monument
	- Pha That Luang
	- Wat Sisaket
  Local Dishes:
	- Sai Oua
	- Nam Khao
	- Khao Poon Nam Paa

PHNOM PENH
Country: Cambodia
Population: 3.5 million
  Famous Landmarks:
	- Royal Palace Phnom Penh
	- Silver Pagoda
	- Independence Monument
  Local Dishes:
	- Amok
	- Kuy Teav
	- Lap Khmer

NAYPYIDAW
Country: Myanmar
Population: 0.9 million
  Famous Landmarks:
	- Uppatasanti Pagoda
	- Myoma Market
	- Water Fountain Garden
  Local Dishes:
	- Nan Gyi Thoke
	- Burmese Tofu
	- Mohinga


PART 3 FUNCTIONS AND CLASSES

3.

In [3]:
from jacket import *

In [4]:
first_jacket = Jacket('china', 'xl', 'blue', 2020)
print(first_jacket.info())

first_jacket.get_descriptive_name()

first_jacket.hip_size()

MANUFACTURER: CHINA, SIZE:XL, COLOUR:BLUE, YEAR:2020
XL-sized blue jacket made in China in 2020
The jacket has hip size of 97 cm.


In [5]:
second_jacket = Jacket('thailand', 'xxl', 'orange', 2019)
print(second_jacket.info())

second_jacket.get_descriptive_name()

second_jacket.hipsize = 100
second_jacket.hip_size()

MANUFACTURER: THAILAND, SIZE:XXL, COLOUR:ORANGE, YEAR:2019
XXL-sized orange jacket made in Thailand in 2019
The jacket has hip size of 100 cm.


In [6]:
third_jacket = Jacket('bangladesh', 'xs', 'green', 2021)
print(third_jacket.info())

third_jacket.get_descriptive_name()

third_jacket.hipsize = 90
third_jacket.hip_size()

MANUFACTURER: BANGLADESH, SIZE:XS, COLOUR:GREEN, YEAR:2021
XS-sized green jacket made in Bangladesh in 2021
The jacket has hip size of 90 cm.


In [7]:
fourth_jacket = Jacket('vietnam', 's', 'black', 2024)
print(fourth_jacket.info())

fourth_jacket.get_descriptive_name()

fourth_jacket.hip_size()

MANUFACTURER: VIETNAM, SIZE:S, COLOUR:BLACK, YEAR:2024
S-sized black jacket made in Vietnam in 2024
The jacket has hip size of 97 cm.


In [8]:
fifth_jacket = Jacket('india', 'm', 'grey', 2018)
print(fifth_jacket.info())

fifth_jacket.get_descriptive_name()

fifth_jacket.hipsize = 90
fifth_jacket.hip_size()

MANUFACTURER: INDIA, SIZE:M, COLOUR:GREY, YEAR:2018
M-sized grey jacket made in India in 2018
The jacket has hip size of 90 cm.


In [9]:
from jacket import LeatherJacket as lj

In [10]:
sixth_jacket = lj('malaysia', 's', 'blue', 2025, 'suede')
print(sixth_jacket.info())

sixth_jacket.get_descriptive_name()

sixth_jacket.hip_size()

sixth_jacket.describe_type()

MANUFACTURER: MALAYSIA, SIZE:S, COLOUR:BLUE, YEAR:2025
S-sized blue jacket made in Malaysia in 2025
The jacket has hip size of 97 cm.
This jacket is made of suede.


In [11]:
seventh_jacket = lj('indonesia', 's', 'brown', 2025, 'cowhide')
print(seventh_jacket.info())

seventh_jacket.get_descriptive_name()

seventh_jacket.hipsize = 99
seventh_jacket.hip_size()

seventh_jacket.describe_type()

MANUFACTURER: INDONESIA, SIZE:S, COLOUR:BROWN, YEAR:2025
S-sized brown jacket made in Indonesia in 2025
The jacket has hip size of 99 cm.
This jacket is made of cowhide.


In [12]:
eighth_jacket = lj('china', 'xl', 'black', 2022, 'full grain')
print(eighth_jacket.info())

eighth_jacket.get_descriptive_name()

eighth_jacket.hipsize =110
eighth_jacket.hip_size()

eighth_jacket.describe_type()

MANUFACTURER: CHINA, SIZE:XL, COLOUR:BLACK, YEAR:2022
XL-sized black jacket made in China in 2022
The jacket has hip size of 110 cm.
This jacket is made of full grain.


In [13]:
ninth_jacket = lj('china', 'l', 'white', 2023, 'horsehide')
print(ninth_jacket.info())

ninth_jacket.get_descriptive_name()

ninth_jacket.hip_size()

ninth_jacket.describe_type()

MANUFACTURER: CHINA, SIZE:L, COLOUR:WHITE, YEAR:2023
L-sized white jacket made in China in 2023
The jacket has hip size of 97 cm.
This jacket is made of horsehide.


In [14]:
tenth_jacket = lj('thailand', 'xxl', 'black', 2017, 'goatskin')
print(tenth_jacket.info())

tenth_jacket.get_descriptive_name()

tenth_jacket.hipsize =120
tenth_jacket.hip_size()

tenth_jacket.describe_type()

MANUFACTURER: THAILAND, SIZE:XXL, COLOUR:BLACK, YEAR:2017
XXL-sized black jacket made in Thailand in 2017
The jacket has hip size of 120 cm.
This jacket is made of goatskin.


In [15]:
from jacket import PufferJacket as pj

In [21]:
eleventh_jacket = pj('thailand', 'xs', 'yellow', 2020, 'hooded')
print(eleventh_jacket.info())

eleventh_jacket.get_descriptive_name()

eleventh_jacket.hipsize =120
eleventh_jacket.hip_size()

eleventh_jacket.describe_style()

MANUFACTURER: THAILAND, SIZE:XS, COLOUR:YELLOW, YEAR:2020
XS-sized yellow jacket made in Thailand in 2020
The jacket has hip size of 120 cm.
The style of this jacket is hooded.


In [17]:
twelveth_jacket = pj('india', 'xs', 'red', 2025, 'geometric')
print(twelveth_jacket.info())

twelveth_jacket.get_descriptive_name()

twelveth_jacket.hipsize =103
twelveth_jacket.hip_size()

twelveth_jacket.describe_style()

MANUFACTURER: INDIA, SIZE:XS, COLOUR:RED, YEAR:2025
XS-sized red jacket made in India in 2025
The jacket has hip size of 103 cm.
The style of this jacket is geometric.


In [18]:
thirteenth_jacket = pj('bangladesh', 'm', 'blue', 2023, 'lightweight')
print(thirteenth_jacket.info())

thirteenth_jacket.get_descriptive_name()

thirteenth_jacket.hip_size()

thirteenth_jacket.describe_style()

MANUFACTURER: BANGLADESH, SIZE:M, COLOUR:BLUE, YEAR:2023
M-sized blue jacket made in Bangladesh in 2023
The jacket has hip size of 97 cm.
The style of this jacket is lightweight.


In [19]:
fourteenth_jacket = pj('thailand', 'l', 'blue', 2022, 'cropped')
print(fourteenth_jacket.info())

fourteenth_jacket.get_descriptive_name()

fourteenth_jacket.hip_size()

fourteenth_jacket.describe_style()

MANUFACTURER: THAILAND, SIZE:L, COLOUR:BLUE, YEAR:2022
L-sized blue jacket made in Thailand in 2022
The jacket has hip size of 97 cm.
The style of this jacket is cropped.


In [20]:
fifteenth_jacket = pj('malaysia', 'm', 'yellow', 2024, 'longline')
print(fifteenth_jacket.info())

fifteenth_jacket.get_descriptive_name()

fifteenth_jacket.hipsize =115
fifteenth_jacket.hip_size()

fifteenth_jacket.describe_style()

MANUFACTURER: MALAYSIA, SIZE:M, COLOUR:YELLOW, YEAR:2024
M-sized yellow jacket made in Malaysia in 2024
The jacket has hip size of 115 cm.
The style of this jacket is longline.


PART 4 FILES AND EXCEPTIONS

1. a)

In [22]:
moviefile = 'movie.txt'
sportfile = 'sport.txt'

# Opening the file
with open(moviefile) as movie_file:
    movie = movie_file.read()
    print(movie)
    
print("\n")

with open(sportfile) as sport_file:
    sport = sport_file.read()
    print(sport)

Bullet Train
Malam Terlarang
The Amateur
Parasite
Until Dawn



Rowing
Volleyball
Badminton
Boxing
Football



1. b)

In [27]:
with open(moviefile, 'a') as movie_file:
    movie_file.write("\nBullet Train movie follows Ladybug, an assassin who is resolved to carry out his assignments peacefully. However, his latest task places him on a crash course with deadly foes from across the worlds and on the fastest train on the planet.\n")
    movie_file.write("Malam Terlarang is a Malay horror movie about Mawar, an 18 year old lady who is being disturbed by mysterious creatures after her sister's sudden death.\n")
    movie_file.write("The Amateur movie is about a CIA decoder who becomes an unlikely field agent to avenge his wife's death in a terrorist attack.\n")
    movie_file.write("Parasite is a South Korean movie about the Kims, a poor family, who insinuate themselves into the lives of the Parks, a wealthy family, by taking on jobs through deception.\n")
    movie_file.write("Until Dawn is a horror movie about five young adults who return to a remote mountain lodge one year after one of their friends disappeared, only to find themselves hunted by a mysterious threat.")

In [28]:
with open(sportfile, 'a') as sport_file:
    sport_file.write("\nRowing is a sport of racing boats using oars.\n")
    sport_file.write("Volleyball is a team sport in which two teams of six players are separated by a net. Each team tries to score points by grounding a ball on the other team's court under organized rules.\n")
    sport_file.write("Badminton is a racquet sport played using racquets to hit a shuttlecock across a net.\n")
    sport_file.write("Boxing is a combat sport and martial art. Taking place in a boxing ring, it involves two people who throw punches at each other for a predetermined amount of time.\n")
    sport_file.write("Football is a team sport played between two teams of 11 players who use their feet to propel a ball towards opponent's goal post and get the ball into the net.")

1. c)

In [30]:
filename = 'movie.txt'

try:
    with open(filename) as file_name:  # Opening the file
        content = file_name.read()
        print(content)
except FileNotFoundError:
    message = "Sorry, the file " + filename + " does not exist."
    print(message)  # Print the error

Bullet Train
Malam Terlarang
The Amateur
Parasite
Until Dawn




PART 5 NUMPY

In [31]:
import numpy as np

In [32]:
# Two arrays each of sizes: single 1d array, 3x3, 2x4, 4x2 and 5x5
A = np.random.randn(5)
B = np.random.randn(5)
C = np.random.randn(3, 3)
D = np.random.randn(3, 3)
E = np.random.randn(2, 4)
F = np.random.randn(2, 4)
G = np.random.randn(4, 2)
H = np.random.randn(4, 2)
I = np.random.randn(5, 5)
J = np.random.randn(5, 5)

In [33]:
# Operation on single array
# Absolute value of A
np.abs(A)

array([2.74189878, 0.44783424, 0.41348077, 2.04993443, 0.54029154])

In [34]:
# B^2
np.square(B)

array([1.93180838, 0.06571272, 0.09015758, 0.38473709, 0.01084943])

In [35]:
# Sign of each element in C
np.sign(C)

array([[ 1.,  1.,  1.],
       [ 1., -1.,  1.],
       [-1., -1.,  1.]])

In [36]:
# exp^x where x is each element in D
np.exp(D)

array([[4.81313554, 0.30811116, 0.66635959],
       [1.8384738 , 7.27913437, 0.62189495],
       [2.31626053, 0.45493304, 1.0242713 ]])

In [37]:
# Compute the floor of each element (the largest integer less than or equal to each element)
np.floor(E)

array([[ 0., -1., -2., -2.],
       [ 2.,  0.,  1., -1.]])

In [38]:
# Return fractional and integral parts of array as a separate array
np.modf(F)

(array([[-0.23590188, -0.79629656,  0.92627822,  0.33009589],
        [-0.65068391, -0.29295327, -0.03772392, -0.54074735]]),
 array([[-1., -0.,  0.,  0.],
        [-0., -1., -0., -1.]]))

In [39]:
# A multiply by 3
A*3

array([8.22569633, 1.34350273, 1.2404423 , 6.14980329, 1.62087463])

In [40]:
# B divide by 2
B/2

array([ 0.69494755,  0.12817246,  0.15013126, -0.31013589, -0.0520803 ])

In [41]:
# Maximum between E and F
np.maximum(E,F)

array([[ 0.34802439, -0.72648458,  0.92627822,  0.33009589],
       [ 2.37256584,  0.32130168,  1.17994485, -0.31665164]])

In [42]:
# C multiply by D
np.multiply(C,D)

array([[ 3.75255359e-01, -1.34044341e+00, -1.64437813e-01],
       [ 5.99798902e-01, -2.11090509e+00, -3.71317723e-01],
       [-9.33506880e-04,  2.54517409e-01,  4.99764270e-02]])

In [43]:
# A + H
np.add(G,H)

array([[-1.57427671,  1.58206176],
       [ 1.49678696, -2.3802491 ],
       [-0.02023629, -0.46046343],
       [ 0.42298367, -2.80922565]])

In [44]:
# I divide J
np.divide(I,J)

array([[-9.95407953e+00, -4.52046033e-01,  2.86662359e-01,
         1.25706600e+00, -5.08140727e+00],
       [ 3.16602842e-01, -3.81126008e-01,  8.84315847e+00,
         1.35250162e+00, -2.74200843e-01],
       [-5.20068141e-01,  2.06613990e+00,  1.37066476e+00,
        -1.01187837e+01,  5.14423009e+00],
       [-5.69239320e+00,  1.97924711e-01, -2.80677316e+01,
         2.52857408e-01, -2.77801810e+00],
       [-1.36082019e-02, -4.20246128e-01,  1.22682162e+00,
        -1.55177081e+00, -2.55461920e+00]])

In [45]:
# Element-wise modulus (remainder of division)
np.mod(I,J)

array([[ 0.00434558,  1.09296992,  0.32660837, -0.35629134, -0.34003189],
       [ 0.63450116, -1.45678366,  0.16862849, -0.50124097,  1.62933852],
       [-0.34788111,  0.02013606,  0.37436538, -0.09869727, -0.02010354],
       [ 0.02614203, -0.23164475, -0.10452228, -0.14055977, -0.0626501 ],
       [ 0.51968756,  1.078444  ,  0.0991782 , -0.8907754 ,  0.29077557]])

In [46]:
# Sum
np.sum(I)

6.428250514894527

In [47]:
# Cumulative sum of elements starting from 0
np.cumsum(J)

array([ 0.09463271,  2.08927093,  3.22861958,  1.84262791,  1.47246181,
        3.47655363,  1.1226275 ,  1.32262371, -0.09932993,  2.14555903,
        1.42070382,  1.72515039,  2.73513413,  2.62313295,  2.48374773,
        2.56873295,  1.39836496,  1.28624888,  0.73036337,  0.4481327 ,
        0.97498984,  2.83516544,  3.27241743,  1.28509616,  1.93796573])

In [48]:
# Cumulative product of elements starting from 1
np.cumprod(F)

array([-1.23590188,  0.98414441,  0.91159153,  0.30091261, -0.195799  ,
        0.25315895, -0.00955015,  0.01471436])

In [49]:
# Variance
np.var(G)

1.0702890910868514

In [50]:
# Standard Deviation
np.std(E)

1.2026461961398927

In [51]:
# Mean
np.mean(H)

-0.3616122250468528

In [52]:
from numpy.linalg import *

In [53]:
# Diagonal element
np.diag(C)

array([ 0.238811  , -1.06342185,  2.08396312])

In [54]:
# Compute the sum of the diagonal elements
np.trace(D)

3.580342135378495

In [55]:
# Compute the matrix determinant
np.linalg.det(J)

8.295080476858338

In [56]:
# Compute eigen valus and eigen vectors
values, vectors = np.linalg.eig(I)

print("Eigenvalues:")
print(values)

print("Eigenvectors:")
print(vectors)

Eigenvalues:
[-3.71179362+0.j          2.12819695+0.82335647j  2.12819695-0.82335647j
 -0.0298588 +0.j         -0.98362427+0.j        ]
Eigenvectors:
[[-0.68769869+0.j         -0.23336742+0.09255463j -0.23336742-0.09255463j
   0.87832257+0.j          0.21160041+0.j        ]
 [-0.09878021+0.j          0.57905235+0.j          0.57905235-0.j
  -0.37842136+0.j          0.63780935+0.j        ]
 [ 0.23200959+0.j         -0.00962828-0.28741611j -0.00962828+0.28741611j
   0.03791725+0.j         -0.16911886+0.j        ]
 [-0.42139486+0.j         -0.31701353-0.39592986j -0.31701353+0.39592986j
   0.0509755 +0.j          0.33341948+0.j        ]
 [ 0.53470637+0.j         -0.43581601-0.2679129j  -0.43581601+0.2679129j
   0.28514998+0.j          0.63926111+0.j        ]]


In [58]:
# Inverse matrix
np.linalg.inv(D)

array([[-0.38623009,  0.41159973,  1.61468878],
       [-0.48923167,  0.44791617,  0.59051016],
       [-2.5397062 ,  0.29423458,  4.5378604 ]])

In [59]:
# Multiplication matrix (2 x 4 and 4 x 2)
np.dot(E, H)

array([[-0.39530177,  3.35499683],
       [-5.08487373,  3.96055396]])

In [60]:
# Multiplication matrix (4 x 2 and 2 x 4)
np.dot(G, F)

array([[-2.63297658e-01, -5.01198129e-01, -2.04017031e-03,
        -5.80303062e-01],
       [-6.95080386e-01,  1.31733129e+00,  1.58240722e+00,
         3.64954489e+00],
       [-4.79518189e-01,  4.39441758e-01,  8.09424758e-01,
         1.59669421e+00],
       [ 7.79007067e-01,  8.71483083e-01, -3.61613876e-01,
         5.17154342e-01]])

In [61]:
# Multiplication matrix (5 x 5 and 5 x 5)
np.dot(I, J)

array([[-1.28998072e+00,  5.88101997e+00,  9.40870533e-02,
        -2.18442773e-01, -1.22965681e-03],
       [ 8.82726067e-02,  7.98050299e-01,  2.63506885e+00,
        -6.08209043e-02,  1.67350833e+00],
       [ 1.13965927e-02, -2.96749850e+00,  1.51289295e+00,
        -7.77007623e-01,  2.91616592e-01],
       [-2.38989136e+00,  2.16133801e+00,  2.93933407e+00,
        -8.32569958e-01, -2.28017877e-01],
       [-2.57280124e+00, -4.72256982e+00, -6.97740653e-01,
         2.66168542e+00, -3.78625651e+00]])

In [62]:
# Multiplication matrix (3 x 3 and 3 x 3)
np.dot(C, D)

array([[ 1.40883678,  1.65988925, -0.62803192],
       [ 1.55684775, -3.88624329,  0.12402084],
       [ 1.55190709, -2.2814952 ,  0.20392039]])

In [63]:
# Solve the linear system Ix = B for x
np.linalg.solve(I, B)

array([-74.64209456,  32.80511044,  -3.32753274,  -4.63304697,
       -24.62966343])